blank_issues_enabled: false
contact_links:
  - name: 🎨Contact the Author
    url: https://github.com/lumirlumir
    about: Please check the GitHub user profile for a contact email or any relevant links.
